CREATE TABLE IF NOT EXISTS deleted_posts (id TEXT PRIMARY KEY, deleted_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS prevent_deleted_post_insert BEFORE INSERT ON posts WHEN EXISTS(SELECT 1 FROM deleted_posts WHERE id=NEW.id) BEGIN SELECT RAISE(ABORT,'POST_DELETED'); END;
CREATE TRIGGER IF NOT EXISTS prevent_deleted_draft_insert BEFORE INSERT ON editorial_drafts WHEN EXISTS(SELECT 1 FROM deleted_posts WHERE id=NEW.id) BEGIN SELECT RAISE(ABORT,'POST_DELETED'); END;
CREATE TRIGGER IF NOT EXISTS prevent_deleted_schedule_insert BEFORE INSERT ON post_schedules WHEN EXISTS(SELECT 1 FROM deleted_posts WHERE id=NEW.id) BEGIN SELECT RAISE(ABORT,'POST_DELETED'); END;
