'use client';
import type {ReactNode} from 'react';
import type {Settings} from '../content';
import {homeSections,pagePaths,pageNames,type SiteManagement} from '../site-management';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Switch} from '@/components/ui/switch';
export default function AppearanceEditor({settings:s,onChange,media,mode}:{settings:Settings;onChange:(v:SiteManagement)=>void;media:(label:string,value:string,onChange:(v:string)=>void)=>ReactNode;mode:'appearance'|'layout'|'seo'}){
 const m=s.management;function set<K extends keyof SiteManagement>(k:K,v:SiteManagement[K]){onChange({...m,[k]:v})}
 const field=(key:keyof SiteManagement,label:string)=><label className="admin-field">{label}<Input value={String(m[key])} onChange={e=>set(key,e.target.value as never)}/></label>;
 const toggles:Partial<Record<keyof SiteManagement,string>>={showToolsIntro:'Araç Kutusu giriş açıklaması',showCollaboration:'İletişim: markalarla iş birliği bölümü',showContactForm:'İletişim formu',showAboutSocial:'Hakkımda: sosyal hesaplar',showContactSocial:'İletişim: sosyal hesaplar',showToc:'Yazılarda içindekiler',showUpdatedDate:'Yazılarda güncelleme tarihi',showRelated:'Yazılarda ilgili içerikler',showFooterRss:'Alt menüde RSS'};
 if(mode==='seo')return <section className="admin-card"><h2>Sayfalara özel arama görünümü</h2><p className="admin-help">Boş alanlarda sayfanın mevcut başlığı ve açıklaması kullanılır. Yazıların SEO alanları yazı editöründedir.</p>{pagePaths.map((path,i)=><details className="brand-admin-item" key={path}><summary>{pageNames[i]} <small>{path}</small></summary><label className="admin-field">Arama başlığı<Input value={m.pageSeo[path].title} onChange={e=>set('pageSeo',{...m.pageSeo,[path]:{...m.pageSeo[path],title:e.target.value}})}/></label><label className="admin-field">Arama açıklaması<Textarea value={m.pageSeo[path].description} onChange={e=>set('pageSeo',{...m.pageSeo,[path]:{...m.pageSeo[path],description:e.target.value}})}/></label><div className="seo-preview"><small>{path}</small><h3>{m.pageSeo[path].title||pageNames[i]}</h3><p>{m.pageSeo[path].description||'Sayfanın mevcut açıklaması kullanılacak.'}</p></div></details>)}</section>;
 if(mode==='layout')return <div className="admin-form-grid"><section className="admin-card"><h2>Ana sayfa düzeni</h2><p className="admin-help">Bölümleri yukarı/aşağı taşı ve görünürlüğünü seç. Gizlemek, içeriği silmez.</p>{m.homeSections.map((item,i)=>item.id==='featured'?null:<div className="layout-editor-row" key={item.id}><label className="switch-field"><span>{homeSections.find(x=>x.id===item.id)?.label}</span><Switch checked={item.visible} onCheckedChange={visible=>set('homeSections',m.homeSections.map(x=>x.id===item.id?{...x,visible}:x))}/></label><div><Button size="sm" variant="outline" aria-label={homeSections.find(x=>x.id===item.id)?.label+' yukarı'} disabled={i===0} onClick={()=>{const a=[...m.homeSections];[a[i-1],a[i]]=[a[i],a[i-1]];set('homeSections',a)}}>↑ Yukarı</Button> <Button size="sm" variant="outline" aria-label={homeSections.find(x=>x.id===item.id)?.label+' aşağı'} disabled={i===m.homeSections.length-1} onClick={()=>{const a=[...m.homeSections];[a[i+1],a[i]]=[a[i],a[i+1]];set('homeSections',a)}}>↓ Aşağı</Button></div></div>)}<label className="admin-field">Son yazılarda kart sayısı<select value={m.latestCount} onChange={e=>set('latestCount',Number(e.target.value))}>{[1,2,3,4,6,9,12].map(n=><option key={n} value={n}>{n}</option>)}</select></label>{field('heroReadUrl','Ana sayfa birinci buton bağlantısı')}{field('heroAboutUrl','Ana sayfa ikinci buton bağlantısı')}{field('toolsGuideUrl','Araç Kutusu rehber bağlantısı')}</section><section className="admin-card"><h2>Diğer sayfa bölümleri</h2>{Object.entries(toggles).map(([k,label])=><label className="switch-field" key={k}><span>{label}</span><Switch checked={Boolean(m[k as keyof SiteManagement])} onCheckedChange={v=>set(k as keyof SiteManagement,v as never)}/></label>)}<p className="admin-help">Sayfalar adreslerinden açılmaya devam eder. Menü bağlantılarını “Menü ve site metinleri” bölümünden yönetebilirsin.</p></section></div>;
 return <div className="admin-form-grid"><section className="admin-card"><h2>Logo ve görseller</h2>{media('Site logosu',m.logo,v=>set('logo',v))}{field('logoAlt','Logo açıklaması')}{field('monogram','Logo yüklenmediğinde kısa marka adı')}{media('Tarayıcı simgesi',m.favicon,v=>set('favicon',v))}<p className="admin-help">Kare PNG önerilir. Boş bırakırsan mevcut simge kullanılır.</p>{field('heroImageAlt','Ana görselin alternatif metni')}{field('heroArtIndex','Ana görsel sağ alt etiketi')}</section><section className="admin-card"><h2>Renkler ve yazı karakteri</h2><label className="switch-field"><span>Hafif ışık ve hareket efektleri</span><Switch checked={m.premiumMotion} onCheckedChange={v=>set('premiumMotion',v)}/></label><p className="admin-help">Kısa giriş ve hover geçişleri. Cihazın hareket azaltma tercihinde animasyonlar otomatik kapanır.</p><p className="admin-help">Değişiklikler ziyaretçilerin gördüğü sayfalara uygulanır. Metin ile zemin arasında okunabilir bir kontrast seç.</p>{([['background','Sayfa zemini'],['foreground','Ana metin'],['surface','Kart ve yumuşak zemin'],['muted','İkincil metin']] as const).map(([k,label])=><label className="admin-field" key={k}>{label}<div className="color-editor"><input aria-label={label+' renk seçici'} type="color" value={m[k]} onChange={e=>set(k,e.target.value)}/><Input aria-label={label+' renk kodu'} value={m[k]} onChange={e=>set(k,e.target.value)}/></div></label>)}<label className="admin-field">Yazı karakteri<select value={m.font} onChange={e=>set('font',e.target.value as SiteManagement['font'])}><option value="sans">Sade · Arial</option><option value="system">Cihazın sistem yazı karakteri</option><option value="serif">Editoryal · Georgia</option></select></label><div className="theme-preview" style={{background:m.background,color:m.foreground}}><strong>{s.name}</strong><p style={{color:m.muted}}>Teknolojiye kendi perspektifinden bak.</p><span style={{background:s.accent,color:m.foreground}}>Vurgu rengi</span></div></section></div>
}
