'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import type {Post} from '../content';
export default function PublicationCalendar({posts,onEdit}:{posts:Post[];onEdit:(p:Post)=>void}){
 const [month,setMonth]=useState(new Date(Date.now()+10800000).toISOString().slice(0,7));const [year,m]=month.split('-').map(Number);const count=new Date(year,m,0).getDate(),start=(new Date(year,m-1,1).getDay()+6)%7;
 const dated=posts.filter(p=>p.status==='scheduled'||p.status==='published');const day=(p:Post)=>p.scheduledAt?new Date(Date.parse(p.scheduledAt)+10800000).toISOString().slice(0,10):p.date;
 function move(delta:number){const d=new Date(year,m-1+delta,15);setMonth(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'))}
 return <section className="admin-card"><div className="workflow-row calendar-controls"><Button variant="outline" aria-label="Önceki ay" onClick={()=>move(-1)}>←</Button><label>Yayın ayı<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label><Button variant="outline" aria-label="Sonraki ay" onClick={()=>move(1)}>→</Button></div><p className="admin-help">Türkiye saati (UTC+3). Planlanan sürüm, zamanı geldiğinde site ziyaretlerinde otomatik görünür. Bilgisayarının veya panelin açık kalması gerekmez.</p><div className="calendar-scroll"><div className="publication-calendar">{['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].map(d=><strong className="calendar-weekday" key={d}>{d}</strong>)}{Array.from({length:start},(_,i)=><div className="calendar-day blank" key={'b'+i}/>)}{Array.from({length:count},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return <div className="calendar-day" key={date}><span>{i+1}</span>{dated.filter(p=>day(p)===date).map(p=><button key={p.id} className={'calendar-post '+p.status} onClick={()=>onEdit(p)}><small>{p.status==='scheduled'?'Planlandı':'Yayında'}{p.scheduledAt?' · '+new Date(p.scheduledAt).toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'}):''}</small>{p.publicTitle||p.title}</button>)}</div>})}</div></div><h2>Yaklaşan yayınlar</h2>{posts.filter(p=>p.status==='scheduled').sort((a,b)=>(a.scheduledAt||'').localeCompare(b.scheduledAt||'')).map(p=><button className="admin-post-row" key={p.id} onClick={()=>onEdit(p)}><strong>{p.publicTitle||p.title}</strong><small>{new Date(p.scheduledAt!).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</small></button>)}{!posts.some(p=>p.status==='scheduled')&&<p className="empty">Planlanan yayın yok. Yazı editöründen bir yayın zamanı seçebilirsin.</p>}</section>
}
