'use client';
import {useState} from 'react';
import {copyDefaults,copyGroups,type NavItem} from '../site-copy';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';
const groupNames:Record<string,string>={home:'Ana sayfa',articles:'Yazılar',prompts:'Promptlar',collections:'Araç Kutusu ve ekipman',about:'Hakkımda',contact:'İletişim ve iş birliği',privacy:'Gizlilik, kullanım şartları ve çerezler',faq:'Sık sorulan sorular',social:'Sosyal hesaplar',common:'Menü ve ortak metinler'};
function groupFor(key:string){if(/^(terms|cookie)/.test(key))return 'privacy';if(/^faq/.test(key))return 'faq';if(/^share/.test(key))return 'articles';const explicit=Object.entries(copyGroups).find(([,keys])=>keys.includes(key));if(explicit)return explicit[0];if(/^(archive|allArticles|emptyArticles)/.test(key))return 'articles';if(/^(about|journey|topicsLabel|topicsTitle|approach)/.test(key))return 'about';if(/^(contact|direct|collab|selectedWorks|form)/.test(key))return 'contact';if(/^(social|youtube|instagram|tiktok|xDescription)/.test(key))return 'social';if(/^(menu|footer)/.test(key))return 'common';return 'home'}
export default function SiteTextEditor({copy,navigation,onCopy,onNavigation}:{copy:typeof copyDefaults;navigation:NavItem[];onCopy:(v:typeof copyDefaults)=>void;onNavigation:(v:NavItem[])=>void}){
 const [search,setSearch]=useState(''),[group,setGroup]=useState('home');const entries=Object.entries(copyDefaults).filter(([key])=>!['guideLabel','guideEmpty'].includes(key)).filter(([key,value])=>search?(value+' '+copy[key as keyof typeof copy]).toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')):groupFor(key)===group);
 return <><section className="admin-card"><h2>Menü düzeni</h2><p className="admin-help">Bağlantı adlarını değiştir, sırala veya menüden gizle. Gizlenen sayfanın adresi çalışmaya devam eder.</p>{navigation.map((item,i)=><div className="nav-editor-row" key={item.path}><label className="admin-field">{item.path}<Input value={item.label} onChange={e=>onNavigation(navigation.map(x=>x.path===item.path?{...x,label:e.target.value}:x))}/></label><div className="workflow-row"><label><input type="checkbox" checked={item.visible} onChange={e=>onNavigation(navigation.map(x=>x.path===item.path?{...x,visible:e.target.checked}:x))}/> Menüde göster</label><Button variant="outline" size="sm" disabled={i===0} onClick={()=>{const a=[...navigation];[a[i-1],a[i]]=[a[i],a[i-1]];onNavigation(a)}}>Yukarı</Button><Button variant="outline" size="sm" disabled={i===navigation.length-1} onClick={()=>{const a=[...navigation];[a[i+1],a[i]]=[a[i],a[i+1]];onNavigation(a)}}>Aşağı</Button></div></div>)}</section><section className="admin-card copy-editor"><h2>Sayfa metinleri ve butonlar</h2><p className="admin-help">Sayfayı seç veya sitede gördüğün metni ara. Ana başlıklar ve uzun içerikler ilgili sayfanın kendi bölümündedir. Alanın üstünde başlangıç metni, kutuda mevcut metin görünür.</p><div className="copy-toolbar"><label>Sayfa<select value={group} onChange={e=>{setGroup(e.target.value);setSearch('')}}>{Object.entries(groupNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>Tüm metinlerde ara<Input placeholder="Örneğin: Promptu kopyala" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><p className="admin-help">{entries.length} düzenlenebilir alan</p><div className="copy-fields">{entries.map(([key,value])=><label className="admin-field site-copy-field" key={key}><span>{value.length>100?value.slice(0,100)+'…':value}</span><Textarea value={copy[key as keyof typeof copy]} onChange={e=>onCopy({...copy,[key]:e.target.value})} rows={value.length>120?4:2}/></label>)}</div>{!entries.length&&<p>Bu metin bulunamadı. Ana başlık için ilgili sayfanın bölümüne bakabilirsin.</p>}</section></>
}
