import 'server-only';
import {randomBytes,createHash,timingSafeEqual} from 'node:crypto';
import {sign} from './session';
import {env} from './platform';
import {getPosts,getSettings} from '../app/store';
import {istanbulDay,type AnalyticsContent,type AnalyticsEvent,type AnalyticsKind,type AnalyticsMetrics,type AnalyticsReport,type AnalyticsRow} from '../app/analytics-types';
export const db=env.DB;
export function createTicket(){const p=Date.now()+'.'+randomBytes(16).toString('hex');return p+'.'+sign('analytics:'+p)}
export function validTicket(ticket:string){const parts=ticket.split('.');if(parts.length!==3||!/^\d{13}$/.test(parts[0])||!/^[a-f0-9]{32}$/.test(parts[1]))return false;const age=Date.now()-Number(parts[0]);if(age<0||age>48*3600000)return false;const expected=sign('analytics:'+parts[0]+'.'+parts[1]);return parts[2].length===expected.length&&timingSafeEqual(Buffer.from(parts[2]),Buffer.from(expected))}
export const ticketHash=(ticket:string)=>createHash('sha256').update(ticket).digest('hex');
export async function catalog(admin=false):Promise<AnalyticsContent[]>{const [s,posts,live]=await Promise.all([getSettings(admin),getPosts(admin),admin?getPosts():Promise.resolve([])]);const publicById=new Map(live.map(p=>[p.id,p]));return [...posts.filter(p=>!p.demo).map(p=>({kind:'post' as const,id:p.id,title:publicById.get(p.id)?.title||p.publicTitle||p.title,path:'/yazi/'+(publicById.get(p.id)?.slug||p.slug),status:p.status})),...s.prompts.map(p=>({kind:'prompt' as const,id:p.id,title:p.title,path:'/promptlar/'+p.slug,status:p.visible?'published':'hidden'})),...s.gear.map(p=>({kind:'gear' as const,id:p.id,title:p.title,path:'/kullandiklarim',status:p.visible?'published':'hidden'})),...s.tools.map(p=>({kind:'tool' as const,id:p.id,title:p.title,path:'/arac-kutusu',status:p.visible?'published':'hidden'})),...Object.entries({'/':'Ana sayfa','/yazilar':'Yazılar','/promptlar':'Promptlar','/arac-kutusu':'Araç Kutusu','/kullandiklarim':'Kullandıklarım','/hakkimda':'Hakkımda','/iletisim':'İletişim','/gizlilik':'Gizlilik'}).map(([path,title])=>({kind:'page' as const,id:path,title,path,status:'published'}))]}
const allowed:Record<AnalyticsKind,AnalyticsEvent[]>={post:['view','engaged','read'],prompt:['view','engaged','copy'],gear:['view','click'],tool:['view','click'],page:['view']};
export function allowedEvent(kind:AnalyticsKind,event:AnalyticsEvent){return Object.hasOwn(allowed,kind)&&allowed[kind].includes(event)}
export function sourceName(ref:string,utm:string){const sources:Record<string,string>={google:'Google',bing:'Bing',youtube:'YouTube',instagram:'Instagram',tiktok:'TikTok',facebook:'Facebook',x:'X',twitter:'X',newsletter:'Bülten',bulten:'Bülten',chatgpt:'ChatGPT',perplexity:'Perplexity'};if(Object.hasOwn(sources,utm.toLowerCase()))return sources[utm.toLowerCase()];try{const host=new URL(ref).hostname.toLowerCase();if(host===new URL(env.SITE_ORIGIN).hostname)return 'İç bağlantı';for(const [domain,name] of [['google.com','Google'],['google.com.tr','Google'],['bing.com','Bing'],['youtube.com','YouTube'],['youtu.be','YouTube'],['instagram.com','Instagram'],['tiktok.com','TikTok'],['facebook.com','Facebook'],['x.com','X'],['t.co','X'],['chatgpt.com','ChatGPT'],['perplexity.ai','Perplexity']])if(host===domain||host.endsWith('.'+domain))return name;return 'Diğer yönlendirmeler'}catch{return 'Doğrudan / bilinmiyor'}}
export async function record(ticket:string,content:AnalyticsContent,event:AnalyticsEvent,source:string,device:string){const now=Date.now();const view=event==='view'?null:await db.prepare("SELECT created_at FROM analytics_receipts WHERE ticket=? AND kind=? AND content_id=? AND event='view'").bind(ticket,content.kind,content.id).first<{created_at:number}>();const day=istanbulDay(new Date(view?.created_at||now));const statements=[db.prepare('INSERT INTO analytics_content(kind,content_id,title,path,status) VALUES (?,?,?,?,?) ON CONFLICT(kind,content_id) DO UPDATE SET title=excluded.title,path=excluded.path,status=excluded.status').bind(content.kind,content.id,content.title,content.path,content.status),db.prepare('INSERT OR IGNORE INTO analytics_receipts(ticket,kind,content_id,event,created_at) VALUES (?,?,?,?,?)').bind(ticket,content.kind,content.id,event,now),db.prepare('INSERT INTO analytics_daily(day,kind,content_id,event,source,device,total) SELECT ?,?,?,?,?,?,1 WHERE changes()=1 ON CONFLICT(day,kind,content_id,event,source,device) DO UPDATE SET total=total+1').bind(day,content.kind,content.id,event,source,device)];await db.batch(statements)}
const blank=():AnalyticsMetrics=>({views:0,pageViews:0,cardViews:0,engaged:0,reads:0,copies:0,clicks:0});
const metric:Record<string,keyof AnalyticsMetrics>={view:'views',engaged:'engaged',read:'reads',copy:'copies',click:'clicks'};
export function range(from:string,to:string){const valid=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;if(!valid(from)||!valid(to)||from>to||to>istanbulDay())throw Error('Geçerli bir tarih aralığı seç.');const days=(Date.parse(to)-Date.parse(from))/86400000+1;if(days>366)throw Error('Tek raporda en fazla 366 gün seçebilirsin.');return {days,previousFrom:new Date(Date.parse(from)-days*86400000).toISOString().slice(0,10),previousTo:new Date(Date.parse(from)-86400000).toISOString().slice(0,10)}}
export async function report(from:string,to:string,kind:string):Promise<AnalyticsReport>{if(!['all','post','prompt','gear','tool','page'].includes(kind))throw Error('İçerik türü geçersiz.');const period=range(from,to);const current=await catalog(true);const historical=(await db.prepare('SELECT kind,content_id AS id,title,path,status FROM analytics_content').all<AnalyticsContent>()).results;const contents=new Map(historical.map(c=>[c.kind+':'+c.id,{...c,status:'removed'}]));for(const c of current)contents.set(c.kind+':'+c.id,c);const rows=new Map<string,AnalyticsRow>();for(const [key,c] of contents)if(kind==='all'||c.kind===kind)rows.set(key,{...c,...blank(),previousViews:0});
const totals=blank(),previous=blank(),days=new Map<string,AnalyticsMetrics>(),sources=new Map<string,number>(),devices=new Map<string,number>();for(let i=0;i<period.days;i++)days.set(new Date(Date.parse(from)+i*86400000).toISOString().slice(0,10),blank());
const records=(await db.prepare("SELECT day,kind,content_id,event,source,device,total FROM analytics_daily WHERE day>=? AND day<=? AND (?='all' OR kind=?)").bind(period.previousFrom,to,kind,kind).all<{day:string;kind:AnalyticsKind;content_id:string;event:string;source:string;device:string;total:number}>()).results;
for(const r of records){const field=metric[r.event];if(!field)continue;const row=rows.get(r.kind+':'+r.content_id);if(r.day<from){previous[field]+=r.total;if(r.event==='view')previous[r.kind==='gear'||r.kind==='tool'?'cardViews':'pageViews']+=r.total;if(row&&r.event==='view')row.previousViews+=r.total;continue}totals[field]+=r.total;if(r.event==='view')totals[r.kind==='gear'||r.kind==='tool'?'cardViews':'pageViews']+=r.total;if(row)row[field]+=r.total;const d=days.get(r.day);if(d){d[field]+=r.total;if(r.event==='view')d[r.kind==='gear'||r.kind==='tool'?'cardViews':'pageViews']+=r.total;}if(r.event==='view'){sources.set(r.source,(sources.get(r.source)||0)+r.total);devices.set(r.device,(devices.get(r.device)||0)+r.total)}}
const installed=await db.prepare("SELECT value FROM analytics_meta WHERE id='installed_at'").first<{value:string}>();const bounds=await db.prepare('SELECT MIN(day) AS firstEvent,MAX(day) AS lastEvent FROM analytics_daily').first<{firstEvent:string|null;lastEvent:string|null}>();return {from,to,...period,installedAt:installed?.value||'',firstEvent:bounds?.firstEvent||null,lastEvent:bounds?.lastEvent||null,totals,previous,rows:[...rows.values()].sort((a,b)=>b.views-a.views||b.copies-a.copies||a.title.localeCompare(b.title,'tr')),daily:[...days].map(([day,m])=>({day,...m})),sources:[...sources].map(([name,views])=>({name,views})).sort((a,b)=>b.views-a.views),devices:[...devices].map(([name,views])=>({name,views})).sort((a,b)=>b.views-a.views)}}
