import {pageMetadata} from '../seo';
import {AdSlot} from '../ads';

import {Search} from 'lucide-react';
import {Shell,PostCard} from '../site';
import {getPosts,getSettings} from '../store';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
export const dynamic='force-dynamic';
export async function generateMetadata({searchParams}:{searchParams:Promise<{konu?:string;q?:string;etiket?:string}>}){const [s,q]=await Promise.all([getSettings(),searchParams]);return {...pageMetadata(s,'Yazılar',s.ui.archiveDescription,'/yazilar'),...((q.q||q.konu||q.etiket)?{robots:{index:false,follow:true}}:{})}}
export default async function Archive({searchParams}:{searchParams:Promise<{konu?:string;q?:string;etiket?:string}>}){const [s,posts,query]=await Promise.all([getSettings(),getPosts(),searchParams]);const categories=[...new Set(s.categories.split(',').map(x=>x.trim()).filter(Boolean))];const filtered=posts.filter(p=>(!query.konu||p.category===query.konu)&&(!query.etiket||(p.tags||[]).includes(query.etiket))&&(!query.q||(p.title+' '+p.excerpt+' '+p.body+' '+(p.tags||[]).join(' ')).toLocaleLowerCase('tr-TR').includes(query.q.toLocaleLowerCase('tr-TR'))));return <Shell settings={s}><main className="main archive"><section className="page-intro"><span className="section-label">{s.ui.latestLabel}</span><h1>{s.ui.archiveTitle}</h1><p>{s.ui.archiveDescription}</p></section><form action="/yazilar" className="search-form">{query.konu&&<input type="hidden" name="konu" value={query.konu}/>}{query.etiket&&<input type="hidden" name="etiket" value={query.etiket}/>}<Input name="q" defaultValue={query.q} placeholder={s.ui.articleSearch} aria-label="Yazılarda ara"/><Button type="submit" aria-label="Ara"><Search size={18}/></Button></form><nav className="filters" aria-label="Yazı kategorileri"><a className={'filter '+(!query.konu&&!query.etiket?'active':'')} href={'/yazilar'+(query.q?'?q='+encodeURIComponent(query.q):'')}>{s.ui.allLabel}</a>{categories.map(c=><a key={c} className={'filter '+(query.konu===c?'active':'')} href={'/yazilar?konu='+encodeURIComponent(c)+(query.q?'&q='+encodeURIComponent(query.q):'')}>{c}</a>)}</nav><nav className="filters" aria-label="Yazı etiketleri">{[...new Set(posts.flatMap(p=>p.tags||[]))].sort().map(t=><a key={t} className={'filter '+(query.etiket===t?'active':'')} href={'/yazilar?etiket='+encodeURIComponent(t)}>{t}</a>)}</nav><p className="section-label">{filtered.length} {s.ui.articleCount}</p>{filtered.length?<div className="post-grid">{filtered.map((p,i)=><PostCard key={p.id} post={p} index={i} settings={s}/>)}</div>:<div className="empty"><h2>{s.ui.archiveEmpty}</h2><a className="text-link" href="/yazilar">{s.ui.articleBackAll}</a></div>}{!query.q&&!query.konu&&!query.etiket&&filtered.filter(p=>!p.demo).length>=3&&<AdSlot settings={s} placement="archive"/>}</main></Shell>}
