 'use client';
import {useEffect} from 'react';
import {useConsent,readConsent} from './consent';
type Event={kind:string;id:string;event:string};
export function trackPromptCopy(id:string){window.dispatchEvent(new CustomEvent('hk:prompt-copy',{detail:id}))}
export default function Tracker({ticket}:{ticket:string}){const consent=useConsent('analytics');useEffect(()=>{if(!consent)return;if(navigator.doNotTrack==='1'||(navigator as Navigator&{globalPrivacyControl?:boolean}).globalPrivacyControl)return;
let disposed=false,sending=false,retries=0,nextFlush=0;let pending:Event[]=[];const sent=new Set<string>();const first=document.querySelector<HTMLElement>('[data-stat-primary]');const kind=first?.dataset.statKind||'page',id=first?.dataset.statId||location.pathname;const valid=()=>document.visibilityState==='visible';let referrer='';try{referrer=new URL(document.referrer).origin}catch{}const utm=new URLSearchParams(location.search).get('utm_source')||'';
function queue(k:string,i:string,event:string){if(!valid()||disposed)return;const key=k+':'+i+':'+event;if(sent.has(key))return;sent.add(key);pending.push({kind:k,id:i,event})}
async function flush(){if(!readConsent()?.analytics||sending||!pending.length||Date.now()<nextFlush)return;sending=true;const events=pending.splice(0,20);try{const r=await fetch('/api/analytics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticket,events,referrer,utm}),keepalive:true});if(!r.ok&&r.status>=500)throw Error('retry');retries=0}catch{if(retries++<3){pending.unshift(...events);nextFlush=Date.now()+Math.pow(2,retries)*1000}}finally{sending=false}}
let visibleSeconds=0,lastTick=performance.now();const cards=new Map<Element,{since:number;kind:string;id:string}>();const observer=new IntersectionObserver(entries=>{for(const entry of entries){const el=entry.target as HTMLElement;if(entry.intersectionRatio>=.5&&valid())cards.set(el,{since:performance.now(),kind:el.dataset.statKind!,id:el.dataset.statId!});else cards.delete(el)}},{threshold:[0,.5]});document.querySelectorAll('[data-stat-card]').forEach(el=>observer.observe(el));
const tick=setInterval(()=>{const now=performance.now(),elapsed=Math.min(1,(now-lastTick)/1000);lastTick=now;if(!valid())return;visibleSeconds+=elapsed;if(visibleSeconds>=1)queue(kind,id,'view');if(first&&visibleSeconds>=30)queue(kind,id,'engaged');if(kind==='post'&&first&&visibleSeconds>=1){const bounds=first.getBoundingClientRect();const reached=(window.innerHeight-bounds.top)/Math.max(bounds.height,1);if(reached>=.75)queue(kind,id,'read')}for(const [el,c] of cards)if(performance.now()-c.since>=1000)queue(c.kind,c.id,'view');void flush()},250);
function visibility(){lastTick=performance.now();if(valid()){observer.disconnect();document.querySelectorAll('[data-stat-card]').forEach(el=>observer.observe(el))}for(const c of cards.values())c.since=performance.now();if(!valid())void flush()}
function click(e:MouseEvent){if(!e.isTrusted)return;const link=(e.target as Element)?.closest?.('a[data-stat-click]');if(!link)return;const card=link.closest<HTMLElement>('[data-stat-card]');if(!card)return;queue(card.dataset.statKind!,card.dataset.statId!,'view');queue(card.dataset.statKind!,card.dataset.statId!,'click');void flush()}
function copied(e:globalThis.Event){const copyId=(e as CustomEvent<string>).detail;if(kind==='prompt'&&copyId===id){queue(kind,id,'view');queue(kind,id,'copy');void flush()}}
function hide(){void flush()}
document.addEventListener('visibilitychange',visibility);document.addEventListener('click',click);window.addEventListener('hk:prompt-copy',copied);window.addEventListener('pagehide',hide);return()=>{void flush();disposed=true;clearInterval(tick);observer.disconnect();document.removeEventListener('visibilitychange',visibility);document.removeEventListener('click',click);window.removeEventListener('hk:prompt-copy',copied);window.removeEventListener('pagehide',hide)}},[ticket,consent]);return <span hidden data-analytics-ticket={ticket}/>}
