import packagedPosts from '../content/editorial-2026-09.json';
import packagedSettings from '../content/site-settings.json';
import {managementDefaults,type SiteManagement} from './site-management.ts';
import {promptDefaults,type PromptItem} from './prompts.ts';
import {copyDefaults,navigationDefaults,type NavItem} from './site-copy.ts';
import {sectionDefaults,type SectionSettings} from './sections.ts';
export type Post = { id:string; slug:string; title:string; excerpt:string; body:string; category:string; date:string; image:string; featured:boolean; status:'published'|'draft'|'archived'|'scheduled'; demo:boolean; updatedDate?:string; imageAlt?:string; seoTitle?:string; seoDescription?:string; sources?:string; scheduledAt?:string; hasDraft?:boolean; publicTitle?:string };
export type Settings = SectionSettings & {management:SiteManagement;featuredPromptIds:string[];promptHomeTitle:string;promptHomeDescription:string;prompts:PromptItem[];promptTitle:string;promptDescription:string;ui:typeof copyDefaults;navigation:NavItem[]; name:string; tagline:string; heroTitle:string; heroDescription:string; aboutTitle:string; aboutBody:string; portrait:string; heroImage:string; email:string; youtube:string; instagram:string; tiktok:string; x:string; accent:string; categories:string; seoTitle:string; seoDescription:string; googleVerification:string; bingVerification:string; adsHomeSlot:string; adsArchiveSlot:string; adsConsentReady:boolean; adsEnabled:boolean; adsClient:string; adsSlot:string; privacy:string; footer:string };
const builtInSettings:Settings = {
 ...sectionDefaults,management:managementDefaults,featuredPromptIds:['portrait-studio','product-headphones','avatar-clay','portrait-neon'],promptHomeTitle:'Videoda gördün, burada dene.',promptHomeDescription:'Bir görsel seç, promptu kopyala ve kendi fikrine uyarla.',prompts:promptDefaults,promptTitle:'Görseli keşfet.\nPromptu kendine uyarla.',promptDescription:'Videolardaki uzun promptlar, örnek görseller ve daha iyi sonuç almak için küçük notlar. Beğendiğin görseli aç, promptu kopyala ve dene.',ui:copyDefaults,navigation:navigationDefaults,
 name:'Hasan Kökçe', tagline:'TEKNOLOJİ İÇERİK ÜRETİCİSİ', heroTitle:'Teknolojiye\nbir de buradan bak.', heroDescription:'Yeni fikirler, merak uyandıran gelişmeler ve hayatın içinden teknoloji. Araştırıyor, sorguluyor ve seninle paylaşıyorum.',
 aboutTitle:'Merakla başlıyor.\nPaylaşarak büyüyor.', aboutBody:'Merhaba, ben Hasan. Teknolojinin hayatımızı nasıl değiştirdiğini merak ediyor, öğrendiklerimi burada paylaşıyorum.\n\nBu site; yeni fikirleri keşfetmek, teknoloji gündemini anlamak ve ürünlere daha yakından bakmak için buluşma noktamız.\n\nBurada teknoloji haberleri, rehberler ve kişisel notlar bulacaksın. Sosyal medyada başlayan sohbet, burada biraz daha derinleşiyor.',
 portrait:'/images/hasan.jpg',heroImage:'/images/hero.webp',email:'info@hasankokce.com',youtube:'https://www.youtube.com/@iamhasankokce',instagram:'https://instagram.com/iamhasankokce',tiktok:'https://tiktok.com/@iamhasankokce',x:'https://x.com/iamhasankokce',accent:'#b9f66a',categories:'Yapay zekâ,Teknoloji,Rehberler,Dijital yaşam',seoTitle:'',seoDescription:'',googleVerification:'',bingVerification:'',adsHomeSlot:'',adsArchiveSlot:'',adsConsentReady:false,adsEnabled:false,adsClient:'',adsSlot:'',privacy:'Bu site temel işlevleri için gerekli teknolojileri kullanır. İletişim bağlantıları ve sosyal medya platformları kendi gizlilik koşullarına tabidir.\n\nReklamlar etkinleştirildiğinde kullanılan hizmetler ve izin tercihleri bu sayfada güncellenir.',footer:'Merak etmeye devam.'
};
export const defaultSettings:Settings = {...builtInSettings,...packagedSettings,ui:{...builtInSettings.ui,...packagedSettings.ui},management:{...builtInSettings.management,...packagedSettings.management,pageSeo:{...builtInSettings.management.pageSeo,...packagedSettings.management.pageSeo}}} as Settings;
export const seedPosts:Post[]=packagedPosts as Post[];
export function readTime(p:Post){return Math.max(1,Math.ceil(p.body.split(/\s+/).length/200))}
export function dateLabel(s:string){return new Date(s+'T12:00:00').toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'})}
