import expansion from '../content/prompt-expansion.json';
export type PromptItem={id:string;slug:string;title:string;description:string;category:string;tool:string;prompt:string;notes:string;image:string;imageAlt:string;videoUrl:string;visible:boolean};
export const additionalPrompts:PromptItem[]=expansion.map(p=>({...p,tool:"Görsel üreten yapay zekâ araçları",videoUrl:"",visible:true}));
export const promptDefaults:PromptItem[]=[
{id:'portrait-studio',slug:'siyah-beyaz-studyo-portresi',title:'Siyah beyaz stüdyo portresi',description:'Yumuşak yan ışık, sade bir fon ve doğal cilt dokusuyla sinematik bir portre.',category:'Portre',tool:'Görsel üreten yapay zekâ araçları',prompt:'Create a cinematic black-and-white studio portrait of a fictional adult male technology creator. Chest-up framing, plain charcoal background, soft side light from a large window, gentle shadow falloff, natural skin texture, simple black crew-neck shirt, relaxed expression looking slightly away from camera. 85mm portrait lens look, restrained film grain, editorial photography. Vertical 4:5 composition. No text, no logo, no watermark.',notes:'Bu örnekteki kişi kurgusal. Kendi fotoğrafınla çalışacaksan referans görsel destekleyen bir araç kullan ve ilk cümleyi “Create a cinematic black-and-white studio portrait of the person in the uploaded reference photo, preserving their facial features” olarak değiştir.\nReferans için yüzün net göründüğü, filtresiz bir fotoğraf seç.\nFazla pürüzsüz bir sonuç alırsan doğal cilt dokusu isteğini koru, güzellik filtresi istemediğini belirt.\n4:5 oranı dikey bir gönderi içindir; hikâye için 9:16 isteyebilirsin.',image:'/images/prompt-portrait.webp',imageAlt:'Yapay zekâyla oluşturulmuş siyah beyaz stüdyo portresi örneği',videoUrl:'',visible:true},
{id:'product-headphones',slug:'minimal-urun-fotografi',title:'Minimal ürün fotoğrafı',description:'Grafit kulaklık, açık renk bir kaide ve ince lime ışıkla sade bir ürün sahnesi.',category:'Ürün',tool:'Görsel üreten yapay zekâ araçları',prompt:'Create a premium studio product photograph of fictional unbranded over-ear headphones in matte graphite. Place the headphones on a low off-white stone pedestal against a warm white seamless background. Add one narrow lime-green rim light, soft daylight from the left, physically plausible soft shadows and detailed material texture. Three-quarter view, generous negative space, clean technology editorial aesthetic. Vertical 4:5 composition. No text, no logo, no watermark.',notes:'“Over-ear headphones” bölümünü göstermek istediğin ürünle değiştirebilirsin.\nGerçek ürünün şeklini korumak için destekleyen araçlarda referans fotoğraf kullan. Yapay zekâ düğme, bağlantı noktası ve ölçüleri değiştirebilir; yayınlamadan önce karşılaştır.\n“Lime-green rim light” ifadesini kendi marka renginle değiştirebilirsin.\nBu görsel kurgusal bir üründür; gerçek bir ürün fotoğrafı veya inceleme kanıtı değildir.',image:'/images/prompt-product.webp',imageAlt:'Yapay zekâyla oluşturulmuş lime kenar ışıklı grafit kulaklık ürün sahnesi',videoUrl:'',visible:true},
{id:'avatar-clay',slug:'uc-boyutlu-kil-avatar',title:'3D kil avatar',description:'Mat yüzeyler ve küçük yeşil detaylarla yumuşak hatlı bir profil karakteri.',category:'3D',tool:'Görsel üreten yapay zekâ araçları',prompt:'Create a stylized 3D avatar bust of a fictional adult technology creator wearing a charcoal hoodie and round glasses. Friendly calm expression, simplified sculpted forms, matte clay materials, subtle lime-green accents on the hoodie drawstrings. Center the bust on a pale gray background with soft studio lighting and gentle ambient shadows. Refined collectible character aesthetic, no oversized accessories. Vertical 4:5 composition. No text, no logo, no watermark.',notes:'Gözlük, saç ve kıyafet tanımını kendine göre düzenle. Bu örnek belirli bir kişiyi temsil etmez.\nKendi yüzüne benzeyen bir avatar için referans destekleyen bir araç kullan; başkasının fotoğrafını izinsiz yükleme.\nProfil fotoğrafında kullanacaksan 1:1 oranını iste ve daire biçiminde kırpılacağı için kenarlarda boşluk bırak.\nAynı metin her çalıştırmada farklı bir sonuç verebilir. Önce kompozisyonu seç, sonra ayrıntıları düzenle.',image:'/images/prompt-avatar.webp',imageAlt:'Yapay zekâyla oluşturulmuş koyu kapüşonlu ve yuvarlak gözlüklü 3D kil avatar',videoUrl:'',visible:true}
,...additionalPrompts
];
