export type CollectionItem={id:string;title:string;category:string;description:string;note:string;url:string;image:string;imageAlt?:string;buttonLabel?:string;visible:boolean};
export type BrandItem={title:string;body:string};
export type SectionSettings={collabFormats:BrandItem[];collabSteps:BrandItem[];collabFormatsTitle:string;collabProcessTitle:string;collabApproachTitle:string;collabApproachBody:string;collabCtaTitle:string;collabCtaBody:string;contactTitle:string;contactDescription:string;aboutJourney:string;aboutTopics:string;aboutApproach:string;guideTitle:string;guideDescription:string;toolsTitle:string;toolsDescription:string;gearTitle:string;gearDescription:string;collabTitle:string;collabBody:string;collabServices:string;mediaKitUrl:string;tools:CollectionItem[];gear:CollectionItem[];projects:CollectionItem[]};
export const sectionDefaults:SectionSettings={
collabFormatsTitle:'Fikrinize uygun bir anlatım.',
collabProcessTitle:'İlk fikirden yayına, birlikte.',
collabApproachTitle:'Markanızın mesajı.\nBenim anlatım dilim.',
collabApproachBody:'İş birliğinin merkezine izleyiciye faydayı koyuyorum. Markanızın önceliklerini kendi anlatım dilimle birleştirirken, ürünle ilgili değerlendirmelerimi deneyimime dayandırırım. Sponsorlu içerikleri açıkça belirtir, güveni uzun vadeli bir ilişkinin temeli olarak görürüm.',
collabCtaTitle:'Bir sonraki içeriği birlikte planlayalım.',
collabCtaBody:'Markanızı ve ürününüzü, ulaşmak istediğiniz kitleyi, kampanya hedefinizi, düşündüğünüz yayın tarihini ve bütçe aralığınızı paylaşın. Bu bilgiler üzerinden uygun formatı, kapsamı ve çalışma takvimini birlikte netleştirelim.',
collabFormats:[
{title:'Kısa video & Reels',body:'Ürünün öne çıkan faydasını tek bir güçlü fikir etrafında anlatan, ilk anından itibaren merak uyandırmayı amaçlayan dikey videolar. Yeni ürün duyuruları ve kullanım senaryoları için birlikte bir kurgu oluşturabiliriz.'},
{title:'Ürün deneyimi',body:'Bir cihazı ya da aksesuarı günlük hayatın içine yerleştiren deneyim içerikleri. Özellikleri somut örneklerle açıklayarak, ürünün kime ve hangi ihtiyaca hitap ettiğini anlaşılır hale getirebiliriz.'},
{title:'Uygulama & araç rehberleri',body:'Uygulamanızın veya dijital ürününüzün değerini adım adım gösteren anlatımlar. Bir özelliği tanıtabilir, başlangıç rehberi hazırlayabilir veya gerçek bir sorunun nasıl çözüldüğünü gösterebiliriz.'},
{title:'Marka kanalları için içerik',body:'Markanızın kendi sosyal medya hesaplarında kullanabileceği video ve anlatım içerikleri. Formatı, teslim edilecek dosyaları ve organik ya da reklam amaçlı kullanım haklarını proje özelinde belirleyebiliriz.'}
],
collabSteps:[
{title:'Hedefi ve uyumu netleştiririz.',body:'Önce ürününüzü, kampanya hedefinizi ve ulaşmak istediğiniz kitleyi konuşuruz. İçeriğin izleyiciye sağlayacağı faydayı ve benim içerik alanlarımla uyumunu değerlendirir, ortak bir başlangıç noktası belirleriz.'},
{title:'Fikri somut bir plana dönüştürürüz.',body:'Ana mesajı, içerik fikrini, platformları ve teslimleri birlikte netleştiririz. Ücret, takvim, geri bildirim kapsamı ve kullanım hakları üzerinde üretim öncesinde anlaşırız; böylece iki taraf da ne bekleyeceğini bilir.'},
{title:'Deneyimler, üretir ve gözden geçiririz.',body:'Ürünü veya hizmeti tanıdıktan sonra anlatımı geliştirir, çekim ve kurguyu hazırlanan plana göre yürütürüm. Kararlaştırdığımız inceleme aşamasında ürün bilgilerinin doğruluğunu ve marka mesajını birlikte kontrol eder, geri bildirimleri belirlenen kapsamda ele alırız.'},
{title:'Yayınlar, teslim eder ve değerlendiririz.',body:'Onaylanan içerik, anlaşılan takvim ve kanallarda yayınlanır veya markanıza teslim edilir. Kendi kanallarımdaki yayınlar için kararlaştırılan kapsamda erişilebilen performans verilerini değerlendirir, sonraki içeriklere yön verecek çıkarımları konuşabiliriz.'}
],
contactTitle:'Bir mesajla başlayalım.',contactDescription:'Bir sorunun, içerik önerin veya birlikte hayata geçirmek istediğin bir fikrin varsa bana yaz.',aboutJourney:'Sosyal medyada teknoloji, mobil cihazlar ve dijital trendler üzerine içerikler paylaşıyorum. Burada ise kısa videolara sığmayan ayrıntılara, rehberlere ve kişisel notlarıma yer açıyorum.',aboutTopics:'Teknoloji ve mobil cihazlar\nUygulamalar ve pratik ipuçları\nYapay zekâ ve dijital yaşam',aboutApproach:'Bir ürünün özelliklerinin günlük hayatta ne anlama geldiğine odaklanıyorum. Teknik ayrıntıları anlaşılır bir dille aktarmak ve merak ettiğim soruları birlikte araştırmak istiyorum.',guideTitle:'Birlikte çözelim.',guideDescription:'Telefon ipuçları, uygulama anlatımları ve adım adım teknoloji rehberleri.',toolsTitle:'Küçük araçlar.\nBüyük kolaylıklar.',toolsDescription:'Paylaştığım kestirmeler, faydalı uygulamalar ve dijital yardımcılar tek bir yerde.',gearTitle:'Masamda neler var?',gearDescription:'İçerik üretirken ve günlük hayatımda kullandığım ekipmanlar.',collabTitle:'Ürününüzün hikâyesini,\nhayatın içinden anlatalım.',collabBody:'İyi bir teknoloji içeriği, insanların bir ürünü kendi hayatlarında hayal etmesini sağlar. Ürününüzün hangi ihtiyaca yanıt verdiğini; anlaşılır anlatım, gerçek kullanım senaryoları ve platforma uygun bir kurgu ile görünür kılmayı hedefliyorum.\n\nMobil cihazlardan uygulamalara, yapay zekâ araçlarından günlük yaşamı kolaylaştıran aksesuarlara kadar, markanızın mesajını izleyicinin merak ettiği sorularla buluşturan içerikler tasarlayabiliriz.',collabServices:'Ürün tanıtımı ve deneyim içerikleri\nInstagram Reels ve kısa videolar\nUygulama ve dijital araç anlatımları\nMarkalar için içerik üretimi',mediaKitUrl:'',tools:[{id:'shortcut-bg',title:'Arka Plan SİL',category:'iPhone kestirmesi',description:'Sosyal hesaplarımda paylaştığım arka plan silme kestirmesi.',note:'Kestirmeyi açarak adımlarını ve istediği izinleri inceleyebilirsin.',url:'https://www.icloud.com/shortcuts/168ccd3423c14cdd8f53edee7bc354e5',image:'',visible:true},{id:'shortcut-park',title:'Arabamı PARK ETTİM',category:'iPhone kestirmesi',description:'Park yeri için paylaştığım kestirmeye buradan ulaşabilirsin.',note:'iPhone Kestirmeler uygulamasında açılır.',url:'https://www.icloud.com/shortcuts/011aaf76a5ea41009af428daba1b6a72',image:'',visible:true}],gear:[{id:'camera',title:'Fujifilm X-S20',category:'Kamera',description:'İçerik üretim ekipmanım.',note:'',url:'',image:'',visible:true},{id:'mic',title:'Fifine AmpliGame A6T',category:'Mikrofon',description:'Ses kayıt ekipmanım.',note:'',url:'',image:'',visible:true}],projects:[]};
