import {env} from '../runtime/platform';
import {defaultSettings,seedPosts,type Settings,type Post} from './content';
export function database(){if(!env.DB)throw new Error('Storage unavailable');return env.DB}
export async function getSettings(admin=false):Promise<Settings>{const row=await database().prepare('SELECT data FROM settings WHERE id = ?').bind('site').first<{data:string}>();const settings:Settings={...defaultSettings,...(row?JSON.parse(row.data):{})};settings.navigation=settings.navigation.map(i=>(i.path as string)==='/rehberler'?{...i,path:'/promptlar' as const,label:'Promptlar'}:i).filter((i,n,a)=>a.findIndex(x=>x.path===i.path)===n);settings.ui={...defaultSettings.ui,...settings.ui};settings.management={...defaultSettings.management,...settings.management,pageSeo:{...defaultSettings.management.pageSeo,...settings.management?.pageSeo}};if(!admin){settings.prompts=settings.prompts.filter(i=>i.visible);settings.tools=settings.tools.filter(i=>i.visible);settings.gear=settings.gear.filter(i=>i.visible);settings.projects=settings.projects.filter(i=>i.visible)}return settings}
export async function getPosts(admin=false):Promise<Post[]>{
 const db=database();await releaseDueSchedules();const [{results},init,schedules]=await Promise.all([db.prepare('SELECT data FROM posts ORDER BY date DESC').all<{data:string}>(),db.prepare('SELECT id FROM settings WHERE id=?').bind('initialized').first(),db.prepare('SELECT id,data,publish_at FROM post_schedules ORDER BY publish_at').all<{id:string;data:string;publish_at:string}>()]);
 const all=new Map<string,Post>((!init&&!results.length?seedPosts:results.map(r=>JSON.parse(r.data))).map(p=>[p.id,p]));
 const now=new Date().toISOString();for(const row of schedules.results){if(row.publish_at<=now||admin){const p:Post={...JSON.parse(row.data),status:row.publish_at<=now?'published':'scheduled',scheduledAt:row.publish_at};if(row.publish_at<=now&&p.featured)for(const old of all.values())old.featured=false;all.set(p.id,p)}}
 if(admin){const drafts=await db.prepare('SELECT id,data FROM editorial_drafts').all<{id:string;data:string}>();for(const row of drafts.results){const d:Post=JSON.parse(row.data),live=all.get(row.id);const hasDraft=!live||Object.entries(d).some(([k,v])=>k!=='status'&&k!=='date'&&v!==(live as unknown as Record<string,unknown>)[k]);all.set(row.id,{...d,status:live?.status||d.status||'draft',date:live?.date||d.date,publicTitle:live?.title,scheduledAt:live?.scheduledAt,hasDraft})}}
 return [...all.values()].filter(p=>admin||p.status==='published').sort((a,b)=>b.date.localeCompare(a.date));
}
export async function initializeContent(){const db=database();const statements=seedPosts.map(p=>db.prepare("INSERT OR IGNORE INTO posts (id,slug,status,date,data) SELECT ?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM settings WHERE id='initialized')").bind(p.id,p.slug,p.status,p.date,JSON.stringify(p)));statements.push(db.prepare("INSERT OR IGNORE INTO settings (id,data) VALUES ('initialized','true')"));await db.batch(statements)}
export async function savePost(post:Post){await initializeContent();const db=database();const statements=[db.prepare('DELETE FROM post_schedules WHERE id=?').bind(post.id)];if(post.featured)statements.push(db.prepare("UPDATE posts SET data=json_set(data,'$.featured',json('false')) WHERE id != ?").bind(post.id));statements.push(db.prepare('INSERT INTO posts (id,slug,status,date,data) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,status=excluded.status,date=excluded.date,data=excluded.data').bind(post.id,post.slug,post.status,post.date,JSON.stringify(post)));await db.batch(statements)}
export function siteOrigin(){return env.SITE_ORIGIN||'http://localhost:5173'}

// Publish due snapshots atomically on reads, so scheduled content never depends on an open browser.
export async function releaseDueSchedules(){const db=database(),now=new Date().toISOString();const due=await db.prepare('SELECT id FROM post_schedules WHERE publish_at<=? LIMIT 1').bind(now).first();if(!due)return;await db.batch([
 db.prepare("UPDATE posts SET data=json_set(data,'$.featured',json('false')) WHERE EXISTS(SELECT 1 FROM post_schedules WHERE publish_at<=? AND json_extract(data,'$.featured')=1)").bind(now),
 db.prepare("INSERT INTO posts(id,slug,status,date,data) SELECT id,json_extract(data,'$.slug'),'published',json_extract(data,'$.date'),CASE WHEN json_extract(data,'$.featured')=1 THEN json_set(data,'$.featured',json(CASE WHEN id=(SELECT id FROM post_schedules WHERE publish_at<=? AND json_extract(data,'$.featured')=1 ORDER BY publish_at DESC,id DESC LIMIT 1) THEN 'true' ELSE 'false' END)) ELSE data END FROM post_schedules WHERE publish_at<=? ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,status=excluded.status,date=excluded.date,data=excluded.data").bind(now,now),
 db.prepare('DELETE FROM post_schedules WHERE publish_at<=?').bind(now)
])}
