import {managementDefaults,homeSections,pagePaths} from './site-management.ts';
import {promptDefaults} from './prompts.ts';
import {copyDefaults,navigationDefaults} from './site-copy.ts';
import {z} from 'zod';
import {sectionDefaults} from './sections.ts';
const brandItems=z.array(z.object({title:z.string().trim().min(1).max(150),body:z.string().trim().min(1).max(3000)})).max(12);
const image=z.string().max(2000).refine(v=>!v||/^\/images\/[a-zA-Z0-9_.-]+$/.test(v)||/^\/api\/media\/[a-zA-Z0-9_.-]+$/.test(v)||/^https:\/\/[^\s]+$/.test(v),'Görsel için HTTPS adresi veya yüklenmiş dosya kullanın.');
const social=z.string().max(500).refine(v=>!v||/^https:\/\/[^\s]+$/.test(v),'HTTPS profil bağlantısı gerekli.');
const collectionItem=z.object({id:z.string().min(1).max(100),title:z.string().trim().min(1).max(180),category:z.string().max(80),description:z.string().max(2000),note:z.string().max(4000),url:social,image,imageAlt:z.string().max(500).default(''),buttonLabel:z.string().max(80).default(''),visible:z.boolean()});
const collection=z.array(collectionItem).max(100).refine(items=>new Set(items.map(i=>i.id)).size===items.length,'Kart kimlikleri benzersiz olmalı.');
export const promptItemSchema=z.object({id:z.string().min(1).max(100),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/,'Prompt adresi küçük harf, rakam ve tire içermeli.').max(150),title:z.string().trim().min(1).max(180),description:z.string().max(1000),category:z.string().max(80),tool:z.string().max(120),prompt:z.string().max(30000),notes:z.string().max(10000),image,imageAlt:z.string().max(500),videoUrl:social,visible:z.boolean()}).superRefine((p,ctx)=>{if(p.visible){for(const key of ['prompt','image','imageAlt'] as const)if(!p[key].trim())ctx.addIssue({code:'custom',path:[key],message:'Yayınlamak için prompt metni, görsel ve görsel açıklaması gerekli.'})}});
const prompts=z.array(promptItemSchema).max(100).refine(a=>new Set(a.map(p=>p.id)).size===a.length&&new Set(a.map(p=>p.slug)).size===a.length,'Prompt kimlikleri ve adresleri benzersiz olmalı.');
export const postSchema=z.object({updatedDate:z.string().refine(v=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,"Güncelleme tarihi geçersiz.").default(''),imageAlt:z.string().max(500).default(''),seoTitle:z.string().max(150).default(''),seoDescription:z.string().max(500).default(''),sources:z.string().max(10000).default(''),id:z.string().min(1).max(100),slug:z.string().min(1).max(150).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),title:z.string().trim().min(3).max(180),excerpt:z.string().trim().min(5).max(500),body:z.string().min(10).max(100000),category:z.string().trim().min(1).max(60),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v),image,featured:z.boolean(),status:z.enum(['draft','published','archived']),demo:z.boolean()});
const safeLink=z.string().max(2000).refine(v=>/^https:\/\/[^\s]+$/.test(v)||(/^\/(?!\/)[^\s\\]*$/.test(v)),'Site içi / adresi veya HTTPS bağlantısı kullanın.');
const color=z.string().regex(/^#[a-fA-F0-9]{6}$/,'Renk altı haneli HEX olmalı.');
const managementSchema=z.object({premiumMotion:z.boolean().default(true),
 logo:image.default(''),logoAlt:z.string().max(200).default(managementDefaults.logoAlt),monogram:z.string().trim().min(1).max(6).default('hk.'),favicon:image.default(''),heroImageAlt:z.string().max(500).default(managementDefaults.heroImageAlt),heroArtIndex:z.string().max(80).default(managementDefaults.heroArtIndex),
 background:color.default(managementDefaults.background),foreground:color.default(managementDefaults.foreground),surface:color.default(managementDefaults.surface),muted:color.default(managementDefaults.muted),font:z.enum(['sans','serif','system']).default('sans'),
 homeSections:z.array(z.object({id:z.enum(homeSections.map(x=>x.id) as ['hero','topics','featured','latest','ad','prompts','about','social']),visible:z.boolean()})).length(8).refine(a=>new Set(a.map(x=>x.id)).size===8,'Her ana sayfa bölümü bir kez bulunmalı.').default(managementDefaults.homeSections),latestCount:z.number().int().min(1).max(12).default(3),
 heroReadUrl:safeLink.default('/yazilar'),heroAboutUrl:safeLink.default('/hakkimda'),toolsGuideUrl:safeLink.default(managementDefaults.toolsGuideUrl),
 ...Object.fromEntries(['showToolsIntro','showCollaboration','showContactForm','showAboutSocial','showContactSocial','showToc','showUpdatedDate','showRelated','showFooterRss','showFooterAdmin'].map(k=>[k,z.boolean().default(k!=='showFooterAdmin')])) as {[K in 'showToolsIntro'|'showCollaboration'|'showContactForm'|'showAboutSocial'|'showContactSocial'|'showToc'|'showUpdatedDate'|'showRelated'|'showFooterRss'|'showFooterAdmin']:z.ZodDefault<z.ZodBoolean>},
 pageSeo:z.object(Object.fromEntries(pagePaths.map(p=>[p,z.object({title:z.string().max(150).default(''),description:z.string().max(500).default('')}).default({title:'',description:''})])) as {[K in typeof pagePaths[number]]:z.ZodDefault<z.ZodObject<{title:z.ZodDefault<z.ZodString>;description:z.ZodDefault<z.ZodString>}>>}).default(managementDefaults.pageSeo)
}).default(managementDefaults);
export const settingsSchema=z.object({management:managementSchema,featuredPromptIds:z.array(z.string().max(100)).max(4).refine(a=>new Set(a.filter(Boolean)).size===a.filter(Boolean).length,"Aynı promptu iki kez seçme.").default(['portrait-studio','product-headphones','avatar-clay','portrait-neon']),promptHomeTitle:z.string().trim().min(1).max(150).default('Videoda gördün, burada dene.'),promptHomeDescription:z.string().max(1000).default('Bir görsel seç, promptu kopyala ve kendi fikrine uyarla.'),prompts:prompts.default(promptDefaults),promptTitle:z.string().trim().min(1).max(150).default("Görseli keşfet. Promptu kendine uyarla."),promptDescription:z.string().max(1000).default("Videolardaki promptlar ve kullanım notları."),seoTitle:z.string().max(150).default(''),seoDescription:z.string().max(500).default(''),googleVerification:z.string().regex(/^[a-zA-Z0-9_-]*$/).max(200).default(''),bingVerification:z.string().regex(/^[a-zA-Z0-9_-]*$/).max(200).default(''),adsHomeSlot:z.string().regex(/^(?:[0-9]{10})?$/).default(''),adsArchiveSlot:z.string().regex(/^(?:[0-9]{10})?$/).default(''),adsConsentReady:z.boolean().default(false),ui:z.object(Object.fromEntries(Object.entries(copyDefaults).map(([k,v])=>[k,z.string().max(3000).default(v)])) as {[K in keyof typeof copyDefaults]:z.ZodDefault<z.ZodString>}).default(copyDefaults),navigation:z.array(z.object({path:z.enum(['/','/yazilar','/promptlar','/arac-kutusu','/kullandiklarim','/hakkimda','/iletisim']),label:z.string().trim().min(1).max(40),visible:z.boolean()})).max(7).refine(a=>new Set(a.map(i=>i.path)).size===a.length).default(navigationDefaults),
collabFormats:brandItems.default(sectionDefaults.collabFormats),collabSteps:brandItems.default(sectionDefaults.collabSteps),
collabFormatsTitle:z.string().min(1).max(150).default(sectionDefaults.collabFormatsTitle),collabProcessTitle:z.string().min(1).max(150).default(sectionDefaults.collabProcessTitle),collabApproachTitle:z.string().min(1).max(150).default(sectionDefaults.collabApproachTitle),collabApproachBody:z.string().max(5000).default(sectionDefaults.collabApproachBody),collabCtaTitle:z.string().min(1).max(150).default(sectionDefaults.collabCtaTitle),collabCtaBody:z.string().max(5000).default(sectionDefaults.collabCtaBody),
contactTitle:z.string().min(1).max(150),contactDescription:z.string().max(1000),aboutJourney:z.string().max(10000),aboutTopics:z.string().max(3000),aboutApproach:z.string().max(10000),guideTitle:z.string().min(1).max(150),guideDescription:z.string().max(1000),toolsTitle:z.string().min(1).max(150),toolsDescription:z.string().max(1000),gearTitle:z.string().min(1).max(150),gearDescription:z.string().max(1000),collabTitle:z.string().min(1).max(150),collabBody:z.string().max(10000),collabServices:z.string().max(5000),mediaKitUrl:social,tools:collection,gear:collection,projects:collection,name:z.string().trim().min(2).max(60),tagline:z.string().max(80),heroTitle:z.string().min(3).max(150),heroDescription:z.string().max(500),aboutTitle:z.string().max(150),aboutBody:z.string().max(20000),portrait:image,heroImage:image.refine(Boolean,'Ana görsel gerekli.'),email:z.union([z.literal(''),z.string().email()]),youtube:social,instagram:social,tiktok:social,x:social,accent:z.string().regex(/^#[a-fA-F0-9]{6}$/),categories:z.string().min(2).max(300),adsEnabled:z.boolean(),adsClient:z.string().refine(v=>!v||/^ca-pub-\d{16}$/.test(v),'AdSense yayıncı kimliği geçersiz.'),adsSlot:z.string().refine(v=>!v||/^\d{10}$/.test(v),'Reklam alanı kimliği 10 haneli olmalı.'),privacy:z.string().max(30000),footer:z.string().max(200)}).refine(s=>!s.adsEnabled||(s.adsClient&&(s.adsSlot||s.adsHomeSlot||s.adsArchiveSlot)&&s.adsConsentReady),'Reklamları açmak için yayıncı kimliği, en az bir alan ve izin hazırlığı onayı gerekli.');
