import {env} from '../../../../runtime/platform';
import {guard,isAdmin} from '../../../auth';
import {database,getSettings,getPosts} from '../../../store';
export async function POST(request:Request){const denied=await guard(request);if(denied)return denied;try{if(Number(request.headers.get('content-length')||0)>6*1024*1024)return Response.json({error:'En fazla 5 MB yükleyebilirsiniz.'},{status:413});const form=await request.formData();const file=form.get('file');if(!(file instanceof File)||file.size>5*1024*1024)return Response.json({error:'En fazla 5 MB PNG, JPEG veya WebP seçin.'},{status:400});const bytes=new Uint8Array(await file.arrayBuffer());const mime=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71?'image/png':bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP'?'image/webp':null;if(!mime||mime!==file.type)return Response.json({error:'Desteklenmeyen görsel dosyası.'},{status:400});const key=crypto.randomUUID()+'.'+({'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[mime]);await env.MEDIA.put(key,bytes,{httpMetadata:{contentType:mime}});await database().prepare('INSERT INTO media_library(key,name,alt,created_at) VALUES (?,?,?,?)').bind(key,file.name.slice(0,200),'',new Date().toISOString()).run();return Response.json({url:'/api/media/'+key,key})}catch(e){console.error('media upload',e);return Response.json({error:'Görsel yüklenemedi. Tekrar deneyin.'},{status:503})}}

export async function GET(){if(!await isAdmin())return Response.json({error:'Yetkisiz erişim'},{status:403});const [metadata,stored,settings,posts]=await Promise.all([database().prepare('SELECT key,name,alt,created_at FROM media_library ORDER BY created_at DESC LIMIT 300').all<{key:string;name:string;alt:string}>(),env.MEDIA.list({limit:300}),getSettings(true),getPosts(true)]);const items=new Map(metadata.results.map(i=>[i.key,{...i,url:'/api/media/'+i.key}]));for(const o of stored.objects)if(!items.has(o.key))items.set(o.key,{key:o.key,name:o.key,alt:'',url:'/api/media/'+o.key});const paths=[settings.heroImage,settings.portrait,...posts.map(p=>p.image),...settings.tools.map(p=>p.image),...settings.gear.map(p=>p.image),...settings.projects.map(p=>p.image)].filter(x=>x.startsWith('/images/'));for(const path of paths)if(!items.has(path))items.set(path,{key:path,name:path.split('/').pop()||path,alt:'',url:path});for(const i of metadata.results)if(i.key.startsWith('/images/'))items.set(i.key,{...i,url:i.key});return Response.json([...items.values()],{headers:{'Cache-Control':'no-store'}})}
export async function PATCH(req:Request){const denied=await guard(req);if(denied)return denied;const d=await req.json() as {key:string;alt:string};if(typeof d.key!=='string'||typeof d.alt!=='string'||d.alt.length>500)return Response.json({error:'Geçersiz alternatif metin.'},{status:400});if(!/^\/images\/[a-zA-Z0-9_.-]+$/.test(d.key)&&!await env.MEDIA.head(d.key))return Response.json({error:'Görsel bulunamadı.'},{status:404});await database().prepare('INSERT INTO media_library(key,name,alt,created_at) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET alt=excluded.alt').bind(d.key,d.key.split('/').pop(),d.alt,new Date().toISOString()).run();return Response.json({ok:true})}

export async function DELETE(req:Request){const denied=await guard(req);if(denied)return denied;try{const d=await req.json() as {key?:string;confirm?:string};if(!d||typeof d.key!=='string'||!d.key)return Response.json({error:'Geçersiz görsel anahtarı.'},{status:400});if(d.confirm!=='DELETE')return Response.json({error:'Silme işlemi onaylanmadı.'},{status:400});if(d.key.startsWith('/images/'))return Response.json({error:'Varsayılan sistem görselleri silinemez.'},{status:400});await env.MEDIA.delete(d.key);await database().prepare('DELETE FROM media_library WHERE key = ?').bind(d.key).run();return Response.json({ok:true})}catch(e){console.error('media delete',e);return Response.json({error:'Görsel silinemedi. Tekrar deneyin.'},{status:500})}}

