import {after} from 'next/server';
import {autoTranslate} from '../../../../runtime/translator';
import {guard,isAdmin} from '../../../auth';
import {db,ready,mail,base,digest,token,newsletterSettings,emailBrand} from '../../../../runtime/newsletter';
import {randomUUID} from 'node:crypto';
export async function GET(){if(!await isAdmin())return new Response(null,{status:403});return Response.json({ready:ready(),brand:await emailBrand(),settings:await newsletterSettings(),subscribers:(await db.prepare('SELECT email,status,created_at,confirmed_at FROM newsletter_subscribers ORDER BY created_at DESC LIMIT 1000').all()).results,campaigns:(await db.prepare('SELECT * FROM newsletters ORDER BY created_at DESC LIMIT 100').all()).results,deliveries:(await db.prepare('SELECT campaign,status,COUNT(*) AS count FROM newsletter_deliveries GROUP BY campaign,status').all()).results},{headers:{'Cache-Control':'no-store'}})}
export async function POST(r:Request){const denied=await guard(r);if(denied)return denied;const raw=await r.text();if(raw.length>50000)return new Response(null,{status:413});let v;try{v=JSON.parse(raw)}catch{return new Response(null,{status:400})}try{
if(v.action==='settings'){const s=v.settings;if(!s||typeof s.enabled!=='boolean'||!['title','description','button'].every(k=>typeof s[k]==='string'&&s[k].trim().length>0&&s[k].length<600))throw Error('Bülten alanlarını kontrol et.');await db.prepare("INSERT INTO settings(id,data) VALUES ('newsletter',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind(JSON.stringify({enabled:s.enabled,title:s.title,description:s.description,button:s.button})).run();after(autoTranslate);return Response.json({message:'Bülten alanı kaydedildi.'})}
if(v.action==='save'){const subject=String(v.subject||'').trim(),body=String(v.body||'').trim();if(!subject||subject.length>150||!body||body.length>20000)return Response.json({error:'Başlık (1–150) ve metin (1–20.000 karakter) gerekli.'},{status:400});const id=v.id||randomUUID();if(v.id){const result=await db.prepare("UPDATE newsletters SET subject=?,body=? WHERE id=? AND status='draft'").bind(subject,body,id).run();if(!result.meta.changes)throw Error('Gönderime alınmış bülten düzenlenemez.')}else await db.prepare('INSERT INTO newsletters(id,subject,body,created_at) VALUES (?,?,?,?)').bind(id,subject,body,new Date().toISOString()).run();return Response.json({id,message:'Taslak kaydedildi.'})}
if(v.action==='remove'){await db.prepare("UPDATE newsletter_subscribers SET status='unsubscribed' WHERE email=?").bind(String(v.email)).run();return Response.json({message:'Abonelik durduruldu.'})}
const campaign=await db.prepare('SELECT * FROM newsletters WHERE id=?').bind(String(v.id||'')).first<{id:string;subject:string;body:string;status:string}>();if(!campaign)throw Error('Önce taslağı kaydet.');if(!ready())throw Error('SMTP bağlantısı henüz tanımlanmadı.');
if(v.action==='test'){await mail(process.env.ADMIN_EMAIL!,'[TEST] '+campaign.subject,campaign.body,base()+'/bulten?preview=1');return Response.json({message:'Test e-postası yönetici adresine gönderildi.'})}
if(v.action==='start'){await db.batch([db.prepare("INSERT OR IGNORE INTO newsletter_deliveries(campaign,email,status,updated_at) SELECT ?,email,'queued',? FROM newsletter_subscribers WHERE status='active' AND EXISTS(SELECT 1 FROM newsletters WHERE id=? AND status='draft')").bind(campaign.id,new Date().toISOString(),campaign.id),db.prepare("UPDATE newsletters SET status='sending' WHERE id=? AND status='draft'").bind(campaign.id)]);return Response.json({message:'Gönderim listesi hazır. Sıradaki grubu gönder düğmesiyle devam et.'})}
if(v.action==='batch'){if(campaign.status!=='sending')throw Error('Bülten gönderime açılmamış.');let count=0;for(let i=0;i<5;i++){const recipient=await db.prepare("UPDATE newsletter_deliveries SET status='sending',updated_at=? WHERE rowid=(SELECT rowid FROM newsletter_deliveries WHERE campaign=? AND status='queued' LIMIT 1) RETURNING email").bind(new Date().toISOString(),campaign.id).first<{email:string}>();if(!recipient)break;const subscriber=await db.prepare("SELECT email FROM newsletter_subscribers WHERE email=? AND status='active'").bind(recipient.email).first();if(!subscriber){await db.prepare("UPDATE newsletter_deliveries SET status='skipped' WHERE campaign=? AND email=?").bind(campaign.id,recipient.email).run();continue}const t=token();await db.prepare('INSERT INTO newsletter_unsubscribe(token_hash,email) VALUES (?,?)').bind(digest(t),recipient.email).run();try{await mail(recipient.email,campaign.subject,campaign.body,base()+'/bulten?token='+t+'&action=unsubscribe');await db.prepare("UPDATE newsletter_deliveries SET status='accepted',updated_at=? WHERE campaign=? AND email=?").bind(new Date().toISOString(),campaign.id,recipient.email).run();count++}catch{await db.prepare("UPDATE newsletter_deliveries SET status='uncertain',updated_at=? WHERE campaign=? AND email=?").bind(new Date().toISOString(),campaign.id,recipient.email).run();break}}
const left=await db.prepare("SELECT COUNT(*) AS n FROM newsletter_deliveries WHERE campaign=? AND status IN ('queued','sending')").bind(campaign.id).first<{n:number}>();if(!left?.n)await db.prepare("UPDATE newsletters SET status='finished' WHERE id=?").bind(campaign.id).run();return Response.json({message:count+' e-posta SMTP sunucusuna teslim edildi. Bu sayı gelen kutusuna teslim garantisi değildir.'})}
return Response.json({error:'Geçersiz işlem.'},{status:400})}catch(e){return Response.json({error:e instanceof Error?e.message:'İşlem tamamlanamadı.'},{status:400})}}
