import {guard,isAdmin} from '../../../auth';
import {database,initializeContent,getPosts,releaseDueSchedules} from '../../../store';
import {draftSchema} from '../../../editorial';
import {postSchema} from '../../../validation';
import {z} from 'zod';
export const dynamic='force-dynamic';
const input=z.object({action:z.enum(['draft','publish','schedule','cancel','restore','archive','unarchive']),id:z.string().min(1).max(100),version:z.number().int().nonnegative(),post:z.unknown().optional(),revisionId:z.string().max(100).optional(),publishAt:z.string().datetime().optional()});
export async function GET(req:Request){if(!await isAdmin())return Response.json({error:'Yetkisiz erişim'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'Yazı gerekli.'},{status:400});const db=database();const [draft,history,schedule]=await Promise.all([db.prepare('SELECT data,version,updated_at FROM editorial_drafts WHERE id=?').bind(id).first<{data:string;version:string;updated_at:string}>(),db.prepare('SELECT id,created_at,label FROM editorial_revisions WHERE post_id=? ORDER BY created_at DESC LIMIT 50').bind(id).all(),db.prepare('SELECT publish_at FROM post_schedules WHERE id=?').bind(id).first()]);return Response.json({draft:draft?JSON.parse(draft.data):null,version:Number(draft?.version||0),updatedAt:draft?.updated_at,history:history.results,schedule},{headers:{'Cache-Control':'no-store'}})}
export async function POST(req:Request){const denied=await guard(req);if(denied)return denied;try{const raw=await req.text();if(raw.length>160000)return Response.json({error:'İçerik çok büyük.'},{status:413});const i=input.parse(JSON.parse(raw));const db=database(),now=new Date().toISOString(),token=crypto.randomUUID();
let p;
if(i.action==='restore'){const r=await db.prepare('SELECT data FROM editorial_revisions WHERE id=? AND post_id=?').bind(i.revisionId||'',i.id).first<{data:string}>();if(!r)return Response.json({error:'Sürüm bulunamadı.'},{status:404});p=draftSchema.parse(JSON.parse(r.data))}else p=draftSchema.parse(i.post);
if(p.id!==i.id)return Response.json({error:'Yazı eşleşmiyor.'},{status:400});
await initializeContent();await releaseDueSchedules();
const publishing=i.action==='publish'||i.action==='schedule';
if(publishing){const checked=postSchema.safeParse({...p,status:'published'});if(!checked.success)return Response.json({error:'Başlık, bağlantı adı, açıklama, kategori, tarih ve içerik alanlarını tamamla.'},{status:400});if(i.action==='schedule'&&(!i.publishAt||Date.parse(i.publishAt)<Date.now()+60000))return Response.json({error:'En az bir dakika ileri bir yayın zamanı seç.'},{status:400});await initializeContent();const collision=await db.prepare('SELECT id FROM posts WHERE slug=? AND id!=?').bind(p.slug,p.id).first();if(collision)return Response.json({error:'Bu bağlantı adı başka bir yazıda kullanılıyor.'},{status:409});const current=await db.prepare('SELECT slug,status FROM posts WHERE id=?').bind(p.id).first<{slug:string;status:string}>();if(i.action==='schedule'&&current?.status==='published'&&current.slug!==p.slug)return Response.json({error:'Yayındaki yazıyı zamanlarken mevcut bağlantı adını koru.'},{status:400});}
const data=JSON.stringify({...p,status:i.action==='archive'?'archived':'draft'}),version=i.version+1;
const save=db.prepare('INSERT INTO editorial_drafts(id,data,version,token,updated_at) SELECT ?,?,?,?,? WHERE ?=0 OR EXISTS(SELECT 1 FROM editorial_drafts WHERE id=? AND CAST(version AS INTEGER)=?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,version=excluded.version,token=excluded.token,updated_at=excluded.updated_at WHERE CAST(editorial_drafts.version AS INTEGER)=? RETURNING version').bind(i.id,data,String(version),token,now,i.version,i.id,i.version,i.version);
const label=({draft:'Otomatik / taslak kaydı',publish:'Yayına alındı',schedule:'Yayın planlandı',cancel:'Plan iptal edildi',restore:'Eski sürüm geri yüklendi',archive:'Arşivlendi',unarchive:'Taslaklara alındı'})[i.action];
const baseline=db.prepare("INSERT INTO editorial_revisions(id,post_id,data,created_at,label) SELECT ?,id,data,?,'Başlangıç sürümü' FROM posts WHERE id=? AND NOT EXISTS(SELECT 1 FROM editorial_drafts WHERE id=?) AND ?=0").bind(token+'-initial',now,i.id,i.id,i.version);
const statements=[baseline,save,db.prepare('INSERT INTO editorial_revisions(id,post_id,data,created_at,label) SELECT ?,id,data,?,? FROM editorial_drafts WHERE id=? AND token=?').bind(token,now,label,i.id,token)];
if(publishing){const publication=JSON.stringify({...p,status:'published',...(i.action==='schedule'?{date:new Date(Date.parse(i.publishAt!)+10800000).toISOString().slice(0,10)}:{})});
if(i.action==='publish'){
 if(p.featured)statements.push(db.prepare("UPDATE posts SET data=json_set(data,'$.featured',json('false')) WHERE id!=? AND EXISTS(SELECT 1 FROM editorial_drafts WHERE id=? AND token=?)").bind(i.id,i.id,token));
 statements.push(db.prepare("INSERT INTO posts(id,slug,status,date,data) SELECT ?,?,'published',?,? WHERE EXISTS(SELECT 1 FROM editorial_drafts WHERE id=? AND token=?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,status=excluded.status,date=excluded.date,data=excluded.data").bind(p.id,p.slug,p.date,publication,p.id,token));
}else{
 statements.push(db.prepare("INSERT INTO posts(id,slug,status,date,data) SELECT ?,?,'draft',?,? WHERE EXISTS(SELECT 1 FROM editorial_drafts WHERE id=? AND token=?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug WHERE posts.status!='published'").bind(p.id,p.slug,p.date,JSON.stringify({...p,status:'draft'}),p.id,token));
 statements.push(db.prepare('INSERT INTO post_schedules(id,data,publish_at) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM editorial_drafts WHERE id=? AND token=?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,publish_at=excluded.publish_at').bind(p.id,publication,i.publishAt!,p.id,token));
}}
if(i.action==='archive'||i.action==='unarchive'){const status=i.action==='archive'?'archived':'draft';statements.push(db.prepare("UPDATE posts SET status=?,data=json_set(data,'$.status',?) WHERE id=? AND EXISTS(SELECT 1 FROM editorial_drafts WHERE id=? AND token=?)").bind(status,status,i.id,i.id,token))}
if(['publish','cancel','archive','unarchive'].includes(i.action))statements.push(db.prepare('DELETE FROM post_schedules WHERE id=? AND EXISTS(SELECT 1 FROM editorial_drafts WHERE id=? AND token=?)').bind(i.id,i.id,token));
statements.push(db.prepare('DELETE FROM editorial_revisions WHERE post_id=? AND id NOT IN (SELECT id FROM editorial_revisions WHERE post_id=? ORDER BY created_at DESC LIMIT 50)').bind(i.id,i.id));
const results=await db.batch(statements);if(!results[1].results.length)return Response.json({conflict:true,error:'Bu yazı başka bir sekmede değişti. Metnini kopyalayıp editörü yeniden aç; eski içerikle üzerine yazılmadı.'},{status:409});return Response.json({ok:true,version,updatedAt:now,post:p,posts:await getPosts(true)});
}catch(e){console.error('workflow',e);return Response.json({error:e instanceof z.ZodError?'Alanları kontrol et; taslak kaydedilemedi.':String(e).includes('UNIQUE')?'Bu bağlantı adı zaten kullanılıyor.':'İşlem tamamlanamadı. Metnin editörde korunuyor.'},{status:e instanceof z.ZodError?400:503})}}
