import {Shell} from '../site';
import {getSettings,siteOrigin} from '../store';
import {pageMetadata,JsonLd} from '../seo';
import {ArrowUpRight,Search} from 'lucide-react';
export const dynamic='force-dynamic';
export async function generateMetadata({searchParams}:{searchParams:Promise<{q?:string;konu?:string}>}){const [s,q]=await Promise.all([getSettings(),searchParams]);return {...pageMetadata(s,'Promptlar',s.promptDescription,'/promptlar'),...(q.q||q.konu?{robots:{index:false,follow:true}}:{})}}
export default async function Prompts({searchParams}:{searchParams:Promise<{q?:string;konu?:string}>}){
 const [s,params]=await Promise.all([getSettings(),searchParams]);const q=typeof params.q==='string'?params.q.slice(0,150):'',category=typeof params.konu==='string'?params.konu:'';
 const rawCategories=[...new Set(s.prompts.map(p=>p.category).filter(Boolean))];
 const priority=['Instagram Videoları','Portre','Ürün','3D','Sinematik','Duvar Kağıdı'];
 const categories=rawCategories.sort((a,b)=>{const aIdx=priority.indexOf(a),bIdx=priority.indexOf(b);if(aIdx!==-1&&bIdx!==-1)return aIdx-bIdx;if(aIdx!==-1)return -1;if(bIdx!==-1)return 1;return a.localeCompare(b,'tr');});
 const items=s.prompts.filter(p=>(!category||p.category===category)&&(!q||(p.title+' '+p.description+' '+p.category).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))));
  return <Shell settings={s}><JsonLd data={{'@context':'https://schema.org','@type':'CollectionPage',name:s.promptTitle.replace(/\n/g,' '),description:s.promptDescription,url:siteOrigin()+'/promptlar',mainEntity:{'@type':'ItemList',itemListElement:items.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.title,url:siteOrigin()+'/promptlar/'+p.slug}))}}}/><main className="main archive"><header className="page-intro"><span className="section-label">{s.ui.promptLabel}</span><h1>{s.promptTitle}</h1><p>{s.promptDescription}</p></header><form action="/promptlar" className="search-form prompt-search"><input type="search" name="q" defaultValue={q} placeholder={s.ui.promptSearch} aria-label="Promptlarda ara"/>{category&&<input type="hidden" name="konu" value={category}/>}<button type="submit" aria-label="Ara"><Search size={20}/></button></form><nav className="filters" aria-label="Prompt kategorileri">{['',...categories].map(c=><a key={c} className={'filter '+(category===c?'active':'')} aria-current={category===c?'page':undefined} href={'/promptlar'+(c||q?'?'+new URLSearchParams({...c?{konu:c}:{},...q?{q}:{}}).toString():'')}>{c==='Instagram Videoları'?'🎬 '+c:(c||s.ui.allLabel)}</a>)}</nav><p className="section-label">{items.length} {s.ui.promptCount}</p>{items.length?<div className="prompt-grid">{items.map(p=><a className="prompt-card" key={p.id} href={'/promptlar/'+p.slug}><div className="prompt-card-image"><img src={p.image} alt={p.imageAlt||p.title} loading="lazy" width={800} height={1000}/><span>{s.ui.promptOpen} <ArrowUpRight size={18}/></span></div><div className="prompt-card-body"><span className="section-label">{p.category}</span><h2>{p.title}</h2><p>{p.description}</p></div></a>)}</div>:<div className="empty"><h2>{q||category?s.ui.promptNoMatch:s.ui.promptEmpty}</h2>{(q||category)&&<a className="text-link" href="/promptlar">{s.ui.promptShowAll}</a>}</div>}</main></Shell>
}
