import Share from '../../share';
import {notFound} from 'next/navigation';
import {Shell} from '../../site';
import {getSettings,siteOrigin} from '../../store';
import {pageMetadata,JsonLd,navLabel} from '../../seo';
import {localePath,fixed} from '../../i18n';
import CopyPrompt from '../copy-prompt';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const [s,{slug}]=await Promise.all([getSettings(),params]);const p=s.prompts.find(p=>p.slug===slug);if(!p)return {title:fixed(s.locale).promptNotFound,robots:{index:false}};const meta=pageMetadata(s,p.title,p.description,'/promptlar/'+p.slug);return {...meta,openGraph:{...meta.openGraph,images:[{url:new URL(p.image,siteOrigin()).href,alt:p.imageAlt}]},twitter:{card:'summary_large_image' as const,title:p.title,description:p.description,images:[new URL(p.image,siteOrigin()).href]}}}
export default async function PromptDetail({params}:{params:Promise<{slug:string}>}){const [s,{slug}]=await Promise.all([getSettings(),params]);const p=s.prompts.find(p=>p.slug===slug);if(!p)notFound();const lp=(u:string)=>localePath(s.locale,u);return <Shell settings={s}><main className="main prompt-detail" data-stat-primary data-stat-kind="prompt" data-stat-id={p.id}><a href={lp('/promptlar')} className="text-link">{s.ui.promptBack}</a><div className="prompt-detail-grid"><figure className="prompt-result"><img src={p.image} alt={p.imageAlt||p.title} width={800} height={1000}/><figcaption>{s.ui.promptCaption}</figcaption></figure><article className="prompt-detail-content"><header><span className="section-label">{p.category}</span><h1>{p.title}</h1><p className="prompt-description">{p.description}</p>{p.tool&&<p className="prompt-tool">{s.ui.promptTool} {p.tool}</p>}</header><CopyPrompt id={p.id} text={p.prompt} copy={s.ui} locale={s.locale}/><Share title={p.title} url={siteOrigin()+lp('/promptlar/'+p.slug)} copy={s.ui}/><section className="prompt-instructions"><h2>{s.ui.promptInstructionsTitle}</h2><ol>{s.ui.promptInstructions.split('\n').filter(Boolean).map((line,i)=><li key={i}>{line}</li>)}</ol></section>{p.notes&&<section className="prompt-notes"><h2>{s.ui.promptNotesTitle}</h2><ul>{p.notes.split('\n').filter(Boolean).map((line,i)=><li key={i}>{line}</li>)}</ul></section>}{p.videoUrl&&<a className="pill dark" href={p.videoUrl} target="_blank" rel="noopener noreferrer">{s.ui.promptVideo}</a>}</article></div><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:navLabel(s,'/promptlar','Promptlar'),item:siteOrigin()+lp('/promptlar')},{'@type':'ListItem',position:2,name:p.title,item:siteOrigin()+lp('/promptlar/'+p.slug)}]}}/></main></Shell>}
